name: Run AI News Search

on:
  workflow_dispatch: # Permite iniciar manualmente
  schedule:
    - cron: '0 11 * * *' # Executa todo dia às 11:00 UTC (8h no Brasil)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          NOTION_KEY: ${{ secrets.NOTION_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          SERPAPI_API_KEY: ${{ secrets.SERPAPI_API_KEY }}
        run: python main.py
